# Generated by Django 3.1.7 on 2021-03-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsprep', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
